### ISSUE TITLE
toLowerCase errors

### ISSUE THREAD

**Issue by commuterjoy** [Financial-Times/spoor-enrichment#376]
```
2016-07-07T15:46:48.309046+00:00 app[sqsus.11]: pipeline error level=error error_message="Cannot read property 'toLowerCase' of undefined" error_name=TypeError error_stack="TypeError: Cannot read property 'toLowerCase' of undefined
2016-07-07T15:46:48.309058+00:00 app[sqsus.11]:     at Object.module.exports.Promise [as avro] (/app/server/filters/avro.js:34:41)
2016-07-07T15:46:48.309060+00:00 app[sqsus.11]:     at /app/server/pipelines/v3.js:41:12
2016-07-07T15:46:48.309061+00:00 app[sqsus.11]:     at process._tickDomainCallback (node.js:444:9)"
```

**Comment by adambraimbridge** [comment]
Cheers. Will fix asap

**Comment by adambraimbridge** [comment]
Resolved by https://github.com/Financial-Times/spoor-enrichment/pull/377
